spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/worktrack_db
    username: root
    password: 159159
    driver-class-name: org.mariadb.jdbc.Driver

  batch:
    job:
      enabled: false
